// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFsWj_CFWDDiP0S2PKazviNHD_tnksmI',
    appId: '1:368339589147:web:e40b61c6e70de937d380be',
    messagingSenderId: '368339589147',
    projectId: 'zoctor-c5390',
    authDomain: 'zoctor-c5390.firebaseapp.com',
    storageBucket: 'zoctor-c5390.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw4XuG9qLwZ8NtL4AdAla2x8hJUWaDYlg',
    appId: '1:368339589147:android:264e26ce1806c774d380be',
    messagingSenderId: '368339589147',
    projectId: 'zoctor-c5390',
    storageBucket: 'zoctor-c5390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1e0w1NvqXM4dJGYUPxQshXAXD9kJBYGQ',
    appId: '1:368339589147:ios:53f69e82302e53bad380be',
    messagingSenderId: '368339589147',
    projectId: 'zoctor-c5390',
    storageBucket: 'zoctor-c5390.appspot.com',
    iosBundleId: 'com.example.zoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1e0w1NvqXM4dJGYUPxQshXAXD9kJBYGQ',
    appId: '1:368339589147:ios:53f69e82302e53bad380be',
    messagingSenderId: '368339589147',
    projectId: 'zoctor-c5390',
    storageBucket: 'zoctor-c5390.appspot.com',
    iosBundleId: 'com.example.zoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjFsWj_CFWDDiP0S2PKazviNHD_tnksmI',
    appId: '1:368339589147:web:8de4c8bea8797213d380be',
    messagingSenderId: '368339589147',
    projectId: 'zoctor-c5390',
    authDomain: 'zoctor-c5390.firebaseapp.com',
    storageBucket: 'zoctor-c5390.appspot.com',
  );
}
